AllCops:
  Exclude:
    - files/default/vendor/**/*

Lint/AmbiguousOperator:
  Exclude:
    - 'libraries/_autoload.rb'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - '**/test/**/*'

Style/AccessorMethodName:
  Exclude:
    - 'libraries/matchers.rb'
