sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=keys-centos-7
  - INSTANCE=service-execute-multi-centos-6
  - INSTANCE=service-execute-multi-centos-7
  - INSTANCE=service-execute-multi-fedora-latest
  - INSTANCE=service-execute-multi-debian-8
  - INSTANCE=service-execute-multi-ubuntu-1404
  - INSTANCE=service-execute-multi-ubuntu-1604
  - INSTANCE=service-systemd-multi-centos-7
  - INSTANCE=service-systemd-multi-fedora-latest
  - INSTANCE=service-systemd-multi-debian-8
  - INSTANCE=service-systemd-multi-ubuntu-1604
#  - INSTANCE=service-upstart-multi-ubuntu-1404
  - INSTANCE=service-sysvinit-multi-centos-6

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec rake
      env: UNIT_AND_LINT=1
